import { TimelineItem, Skill, SocialLink, BlogPost, Project } from "./types";
import profil from "./assets/images/profil.jpg";
import spaceMonopoly from "./assets/images/miniatures/projects/space_monopoly.png";
import phoneMarket from "./assets/images/miniatures/projects/phone_market.png";
import fastlink from "./assets/images/miniatures/projects/fastlink.png";
import optimisationRestitution from "./assets/images/miniatures/blogs/optimisation_restitution.jpg";
import escxv from "./assets/images/miniatures/blogs/escxv.jpg";
import rigueur from "./assets/images/miniatures/blogs/rigueur.jpg";
import espritCritique from "./assets/images/miniatures/blogs/esprit_critique.jpg";
import ergonomie from "./assets/images/miniatures/blogs/ergonomie.jpg";
import devBackend from "./assets/images/miniatures/blogs/dev_backend.jpg";
import devFrontend from "./assets/images/miniatures/blogs/dev_frontend.jpg";
import coderPrepremnt from "./assets/images/miniatures/blogs/coder_proprement.png";

export const timelineData: TimelineItem[] = [
  {
    id: 1,
    title: "Expert en ingénierie du logiciel",
    organization: "ESIEA",
    period: "2023 - Présent",
    description: "Titre d'expert en ingénierie du logiciel",
    type: "education",
    location: "Ivry-sur-Seine",
    skills: [
      "Python",
      "Architecture logicielle",
      "Agile",
      "JavaScript",
      "Vision par ordinateur",
      "Flutter",
      "Ionic",
      "Programmation fonctionnelle",
    ],
  },
  {
    id: 2,
    title: "Développeur Full Stack",
    organization: "Urssaf Ile-de-France",
    period: "Nov 2023 - Présent",
    description:
      "Développement de solutions applicatives et automatisées pour les directions métier.",
    type: "experience",
    location: "Montreuil",
    skills: [
      "React.js",
      "Node.js",
      "TypeScript",
      "MySQL",
      "Docker",
      "MongoDB",
      "Administration Système Linux",
    ],
  },
  {
    id: 3,
    title: "Développeur Full Stack",
    organization: "KMB Labs",
    period: "Mar 2023 - Août 2023",
    description:
      "Développement de parcours WhatsApp, chatbots client et lambdas d'envoi de notification, amélioration du backoffice.",
    type: "experience",
    location: "Paris",
    skills: [
      "JavaScript",
      "Node.js",
      "React",
      "API 360 Dialogs",
      "AWS Lambda",
      "Serverless",
      "Programmation fonctionnel",
    ],
  },
  {
    id: 4,
    title: "Ingénieur de support technique",
    organization: "AB Tasty",
    period: "Juil 2022 - Août 2022",
    description:
      "Développement d'une extension Chrome pour visualiser des informations concernant des informations concernant des tests AB (A/B testing).",
    type: "experience",
    location: "Paris",
    skills: [
      "React.js",
      "JavaScript",
      "API Chrome",
      "API AB Tasty",
      "A/B Testing",
    ],
  },
  {
    id: 5,
    title: "Bachelor en informatique",
    organization: "INTECH",
    period: "2020 - 2023",
    description: "Bachelor en informatique (Avec mention)",
    type: "education",
    location: "Ivry-sur-Seine",
    skills: [
      "Java",
      "Spring Boot",
      "Vue.js",
      "DevOps",
      "WAMP",
      "JavaFX",
      "PHP",
      "Microservices",
      "APIs REST",
      "TDD",
      "POO",
      "CI/CD",
      "Node.js",
    ],
  },
  {
    id: 6,
    title: "Baccalauréat Scientifique",
    organization: "Lycée Camille See",
    period: "2017 - 2020",
    description: "Baccalauréat scientifique (Admis)",
    type: "education",
    location: "Paris",
    skills: ["Baccalauréat général", "Spécialité mathématique"],
  },
];
export const skillsData: Skill[] = [
  {
    id: 1,
    name: "React.js",
    level: "Intermediate",
    icon: "Code",
    category: "technical",
  },
  {
    id: 2,
    name: "Node.js",
    level: "Intermediate",
    icon: "Server",
    category: "technical",
  },
  {
    id: 3,
    name: "TypeScript",
    level: "Intermediate",
    icon: "FileType",
    category: "technical",
  },
  {
    id: 4,
    name: "Administration Système Linux",
    level: "Intermediate",
    icon: "Terminal",
    category: "technical",
  },
  {
    id: 5,
    name: "Git",
    level: "Intermediate",
    icon: "GitBranch",
    category: "technical",
  },
  {
    id: 6,
    name: "CSS",
    level: "Intermediate",
    icon: "Palette",
    category: "technical",
  },
  {
    id: 7,
    name: "JavaScript",
    level: "Intermediate",
    icon: "Code",
    category: "technical",
  },
  {
    id: 8,
    name: "Programmation Fonctionnelle",
    level: "Intermediate",
    icon: "Function",
    category: "technical",
  },
  {
    id: 9,
    name: "Docker",
    level: "Intermediate",
    icon: "Box",
    category: "technical",
  },
  {
    id:25,
    name: "Next.js",
    level: "Beginner",
    icon: "Layout",
    category: "technical",
  },
  { id: 10, name: "Agile", level: "Beginner", icon: "Users", category: "soft" },
  { id: 11, name: "Résilience", icon: "Shield", category: "soft" },
  { id: 12, name: "Optimisme", icon: "Smile", category: "soft" },
  { id: 13, name: "Rigueur", icon: "CheckCircle", category: "soft" },
  { id: 14, name: "Discipline", icon: "Clock", category: "soft" },
  { id: 15, name: "Travail d'équipe", icon: "Team", category: "soft" },
  { id: 16, name: "Autonomie", icon: "User", category: "soft" },
  { id: 28, name: "Esprit critique", icon: "Brain", category: "soft" },
  {
    id: 17,
    name: "Anglais",
    level: "Intermediate",
    icon: "Globe",
    category: "language",
  },
  {
    id: 18,
    name: "Français",
    level: "Native",
    icon: "Globe",
    category: "language",
  },
  {
    id: 19,
    name: "Visual Studio Code",
    level: "Intermediate",
    icon: "Code2",
    category: "tools",
  },
  {
    id: 20,
    name: "Postman",
    level: "Intermediate",
    icon: "Server",
    category: "tools",
  },
  {
    id: 21,
    name: "Figma",
    level: "Beginner",
    icon: "Layout",
    category: "tools",
  },
  {
    id: 24,
    name: "SQL",
    level: "Intermediate",
    icon: "Database",
    category: "technical",
  },
];

export const socialLinks: SocialLink[] = [
  { id: 1, name: "GitHub", url: "https://github.com/", icon: "Github" },
  { id: 2, name: "LinkedIn", url: "https://linkedin.com/", icon: "Linkedin" },
  { id: 3, name: "Twitter", url: "https://twitter.com/", icon: "Twitter" },
  { id: 4, name: "Email", url: "mailto:hello@example.com", icon: "Mail" },
];

export const personalInfo = {
  name: "Jérémie Kunkela",
  title: "Développeur Full Stack",
  bio: "Passionné par le développement web, je suis actuellement en alternance chez Urssaf Ile-de-France tout en poursuivant mes études d'ingénieur à l'ESIEA. Je me spécialise dans les technologies modernes gravitant autour du langage Javascript.",
  location: "Paris, France",
  profileImage: profil,
};

export const blogPosts: BlogPost[] = [
  {
    id: 7,
    title: "Optimisation du suivi de restitution du matériel",
    slug: "optimisation-restitution-materiel",
    excerpt:
      "Dans toute entreprise, la gestion et la restitution du matériel informatique lors du départ d’un collaborateur sont des enjeux majeurs pour la sécurité, la maîtrise des coûts et l’optimisation des processus internes. Ce projet vise à fiabiliser et automatiser ce suivi, tout en offrant une meilleure visibilité aux équipes informatiques et RH.",
    content: [
      "Dans de nombreuses entreprises, la restitution du matériel informatique lors du départ d’un employé est un processus critique, souvent source de pertes matérielles, de complexité administrative et de risques de sécurité. Une gestion rigoureuse de ces restitutions contribue directement à l’optimisation de la gestion interne, à la réduction des coûts et à la sécurisation du parc informatique.",
      "Dans mon entreprise, ce processus n’était pas suffisamment suivi, ce qui compliquait le travail des informaticiens locaux (IL) et des ressources humaines (RH). Après une analyse des besoins, nous avons décidé de mettre en place un script automatisé permettant d’identifier les employés sur le départ à J-X jours, de leur envoyer une première notification pour les inviter à prendre rendez-vous avec un informaticien via un outil interne, puis de programmer plusieurs relances si aucune action n’était prise.",
      "Si, après le départ de l’employé, aucun matériel n’était restitué, une nouvelle étape de suivi était déclenchée, informant les RH pour qu’ils puissent engager des actions si nécessaire.",
      "### Automatiser pour fiabiliser le suivi",
      "J’ai choisi de développer ce script en Node.js et TypeScript, afin de garantir la robustesse et la fiabilité du traitement des données. Node.js s’est imposé pour sa performance et sa capacité à s’intégrer facilement avec les outils internes de l’entreprise.",
      "Rapidement, il est apparu qu’une simple automatisation ne suffisait pas : les équipes avaient besoin d’une visibilité en temps réel sur l’état des restitutions. J’ai donc proposé et développé une interface web en React et Node.js, permettant de piloter l’ensemble du processus.",
      "### Une interface pour centraliser l’information",
      "L’interface permet de visualiser qui a pris rendez-vous, qui a restitué ou non son matériel, et qui doit partir dans les prochains jours. Elle offre également la possibilité d’ajouter des commentaires pour suivre les restitutions et de déclarer manuellement des rendez-vous, bien que la plupart soient récupérés automatiquement depuis l’outil interne.",
      "Grâce à cette interface, les IL et les RH disposent d’une vision claire et centralisée du processus. J’ai également ajouté une fonctionnalité permettant d’interrompre le suivi pour des cas spécifiques, par exemple lorsqu’un employé conserve du matériel pour une mission future.",
      "### Un impact concret sur la gestion interne",
      "Depuis la mise en place de ce processus, 90 restitutions ont été gérées avec succès, et seul un employé n’a pas restitué son matériel depuis octobre 2024. Ce projet a permis d’optimiser la gestion interne, de sécuriser le parc informatique et de faciliter le travail des équipes concernées.",
      "### Des perspectives d’évolution",
      "À court terme, des améliorations sont déjà prévues : extension à d’autres types de matériel (par exemple, les chaises ergonomiques), ouverture d’un module RH pour saisir les étapes du processus, et ajout d’une page de statistiques pour suivre l’évolution du taux de restitution.",
      "Le script évoluera également pour prendre en compte davantage de types de contrats, certains n’étant pas encore gérés pour des raisons administratives.",
      "### Un projet à forte valeur ajoutée",
      "Ce projet illustre l’importance d’optimiser les processus internes dans une entreprise, en s’appuyant sur l’automatisation et la centralisation de l’information. Il m’a permis de renforcer mes compétences en développement full-stack et en gestion de projet, tout en apportant une réelle valeur ajoutée à l’organisation.",
      "Si c’était à refaire, j’impliquerais encore plus les utilisateurs finaux dès les premières étapes pour optimiser l’interface et le processus. Aujourd’hui, je suis fier d’avoir contribué à une meilleure gestion interne et à la sécurisation du matériel de l’entreprise.",
    ].join("\n"),
    date: "2025-05-18",
    category: "project",
    readTime: 10,
    image: optimisationRestitution,
    skills: [
      "Node.js",
      "TypeScript",
      "React",
      "Gestion de projet",
      "Automatisation",
      "Ergonomie d'une application",
    ],
  },
  {
    id: 8,
    title: "Développement d’un nouveau site web pour mon club d’athlétisme",
    slug: "refonte-site-club-athletisme",
    excerpt:
      "Refonte complète du site web de mon club d’athlétisme pour améliorer l’ergonomie, la communication et attirer de nouveaux adhérents grâce à Next.js.",
    content: [
      "Depuis 2018, je pratique le court sprint dans mon club d’athlétisme, un sport qui me passionne et que je considère comme mon loisir principal. Cependant, le site web du club était totalement dépassé, tant sur le plan visuel que fonctionnel. Conçu en PHP avec une ergonomie vieillissante, il rendait la navigation difficile et compliquait l’accès aux informations essentielles, comme les horaires d’entraînement, les contacts des coachs et les modalités d’adhésion. Résultat : le club peinait à attirer de nouveaux membres, et la communication avec les adhérents existants était inefficace.",
      "### De la refonte du design à la réécriture complète du site",
      "Au départ, l’objectif était simplement d’améliorer le design du site existant. Cependant, après une analyse approfondie, j’ai démontré que les limitations techniques et ergonomiques de l’ancienne version rendaient cette approche inefficace. Plutôt que d’essayer d’améliorer une base dépassée, j’ai proposé une refonte complète et une réécriture du site avec des technologies modernes.",
      "J’ai choisi Next.js, un framework basé sur React, pour profiter d’un chargement rapide des pages, d’un référencement naturel optimisé et d’une meilleure gestion des routes dynamiques. L’objectif était d’offrir une interface moderne, fluide et agréable à utiliser, tout en rendant l’information plus accessible aux visiteurs.",
      "### Un site plus attractif et fonctionnel",
      "Le nouveau site propose une navigation simplifiée et intuitive, avec des sections claires et accessibles rapidement. Une page dédiée aux horaires d’entraînement et aux contacts des coachs permet aux nouveaux adhérents de trouver facilement les informations dont ils ont besoin. J’ai également intégré une galerie de photos récentes et un module d’actualités pour que le club puisse partager les résultats des compétitions et les événements à venir.",
      "Pour maximiser l’impact du site, j’ai soigné l’aspect visuel en adoptant une approche inspirée des sites modernes, avec une mise en page épurée et dynamique. Le club a ainsi pu bénéficier d’un outil plus attractif pour séduire de nouveaux membres.",
      "### Un projet réalisé en un temps record et déployé gratuitement",
      "Le développement s’est déroulé sur une période de deux semaines, juste avant la rentrée 2023, afin que le site soit opérationnel pour le début de la nouvelle saison. Une fois finalisé, je l’ai déployé gratuitement sur Vercel, une plateforme optimisée pour Next.js, offrant un hébergement performant et sécurisé.",
      "J’ai également géré l’acquisition du nom de domaine via Google Domains, avant qu’il ne soit transféré à Squarespace. Cette étape était essentielle pour garantir une meilleure visibilité du site et assurer un accès simple via une adresse professionnelle.",
      "### Un succès immédiat après les Jeux Olympiques",
      "Les résultats ne se sont pas fait attendre. Avec l’effet des Jeux Olympiques de Paris 2024, le club a reçu une soixantaine de demandes de séances d’essai et d’adhésions, toutes effectuées via le nouveau site. 100 % des nouveaux adhérents post-JO sont passés par cet outil, prouvant son efficacité en tant que support de communication. Les coachs et les bénévoles ont également salué l’ergonomie du site, qui facilite leur travail au quotidien.",
      "Grâce à ce projet, j’ai non seulement pu moderniser l’image de mon club, mais aussi mettre en application mes compétences en développement web dans un cadre concret et utile. Cette expérience m’a également permis de maîtriser Next.js et de gérer un déploiement optimisé, tout en contribuant activement à la vie de mon club.",
    ].join("\n"),
    date: "2024-09-10",
    category: "project",
    readTime: 8,
    image: escxv,
    skills: [
      "Next.js",
      "React",
      "Déploiement",
      "UX/UI",
      "Gestion de projet",
      "SEO",
    ],
  },
  {
    id: 9,
    title: "Refonte de l’outil de gestion de réservation : de GRR à Chronos",
    slug: "refonte-grr-chronos",
    excerpt:
      "Modernisation complète de l’outil de gestion de réservation de ressources, passant de GRR à Chronos, une application performante et ergonomique basée sur Node.js, React et TypeScript.",
    content: [
      "L’entreprise utilisait depuis des années GRR, un outil open-source conçu pour la gestion et la réservation de ressources. Initialement basé sur une application PHP/SQL, il permettait de gérer la réservation de salles et de matériels tout en offrant quelques fonctionnalités d’agenda partagé. Cependant, GRR était devenu obsolète, avec une ergonomie dépassée, une interface peu intuitive et des performances insuffisantes, notamment pour la consultation des disponibilités des salles.",
      "L’idée de base était simplement de revoir le design de l’outil existant, mais j’ai insisté sur la nécessité d’aller au-delà d’une simple refonte graphique. Il est rapidement apparu qu’une réécriture complète de l’application était une solution bien plus adaptée. Cette proposition a été validée par le management, et quelques mois plus tard, la décision s’est révélée encore plus pertinente lorsque les serveurs ont été mis à jour. GRR n’aurait pas été compatible avec les nouvelles infrastructures, ce qui aurait posé de nombreux problèmes techniques.",
      "### Développement de Chronos : un outil performant et ergonomique",
      "J’ai donc développé Chronos, une nouvelle application basée sur Node.js, React et TypeScript. L’objectif était de proposer un outil plus rapide, plus fluide et plus moderne, avec des fonctionnalités adaptées aux besoins réels des utilisateurs.",
      "L’application permet de gérer les réservations et les conflits de réservation en temps réel, tout en offrant une expérience utilisateur optimisée. La recherche de salles a été totalement repensée pour être instantanée et intuitive. J’ai intégré un calendrier dynamique, offrant une meilleure visibilité des créneaux disponibles et des réservations en cours. L’ergonomie a été retravaillée pour que la navigation soit fluide et logique, inspirée d’outils modernes comme Google Calendar.",
      "Des fonctionnalités avancées ont été ajoutées, comme le glisser-déposer pour modifier facilement les réservations, des raccourcis clavier pour les dupliquer en un clic, et des filtres intelligents pour retrouver rapidement une réservation spécifique. Chaque salle affiche désormais des informations détaillées sur son équipement et sa capacité, rendant la gestion des ressources plus efficace.",
      "En plus de l’interface utilisateur, un panneau d’administration a été conçu pour gérer les rôles et les autorisations de réservation. Il permet de contrôler l’accès aux salles, de gérer les espaces et d’adapter l’outil aux besoins spécifiques de l’entreprise. Un système de légendes et de couleurs a été mis en place pour faciliter la lecture des réservations et offrir un filtrage visuel immédiat.",
      "### Un développement progressif et des tests approfondis",
      "L’un des défis majeurs de ce projet a été l’absence de cahier des charges détaillé. Il a fallu analyser l’utilisation existante de GRR et en extraire les fonctionnalités essentielles. Grâce à une collaboration étroite avec les assistantes de direction, nous avons pu définir les besoins réels et les priorités.",
      "Le développement s’est fait de manière itérative, avec des retours réguliers des utilisateurs pour ajuster et améliorer l’outil. Cette approche agile a permis de s’adapter rapidement aux imprévus et d’assurer une livraison dans les délais impartis.",
      "À un moment donné, la pression pour livrer rapidement m’a conduit à coder de manière un peu précipitée, sans toujours respecter les principes de qualité et de maintenabilité. J’ai rectifié cela lors des phases de test et de stabilisation avant le passage en production.",
      "Les tests ont été réalisés en collaboration avec les assistantes de direction, qui sont les principales utilisatrices du système. Leurs retours ont permis d’affiner l’outil et d’apporter des corrections et des améliorations pertinentes.",
      "### Une adoption réussie et un accueil positif",
      "La mise en production de Chronos a été précédée d’une présentation officielle à la direction. L’outil a été très bien accueilli, notamment pour son interface moderne et intuitive, qui tranche avec l’ancienne version de GRR.",
      "Grâce à cette refonte, l’entreprise dispose désormais d’un outil performant, évolutif et compatible avec les infrastructures récentes. Chronos permet non seulement d’améliorer l’efficacité de la gestion des réservations, mais aussi de réduire les pertes de temps liées aux anciennes contraintes techniques et ergonomiques de GRR.",
      "Ce projet a été une expérience enrichissante, combinant analyse des besoins, développement full-stack et gestion de projet agile. Il m’a permis de relever de nombreux défis et d’apporter une solution concrète et innovante à un problème qui affectait le quotidien des employés.",
    ].join("\n"),
    date: "2025-03-01",
    category: "project",
    readTime: 10,
    image: optimisationRestitution,
    skills: [
      "Node.js",
      "React",
      "TypeScript",
      "UX/UI",
      "Gestion de projet",
      "Full-stack",
      "Agile",
    ],
  },
  {
    id: 10,
    title:
      "Développement backend moderne : conception d’API et bonnes pratiques",
    slug: "developpement-backend-api-bonnes-pratiques",
    excerpt:
      "Retour d’expérience sur la conception d’API robustes et la mise en œuvre des bonnes pratiques backend, illustré par les projets de restitution de matériel et Chronos.",
    content: [
      "# Le Développement Backend : Technologies et Concepts Essentiels",
      "",
      "Le développement backend occupe une place centrale dans la création d'applications web performantes et évolutives. Mais qu'est-ce que le backend ? Il s'agit de la partie « invisible » d'un site ou d'une application, qui gère la logique métier, les données et la communication avec le frontend (la partie visible par l'utilisateur).",
      "",
      "## Qu'est-ce qu'une API ?",
      "",
      "Une API (Application Programming Interface) est une interface qui permet à différents logiciels de communiquer entre eux. Par exemple, lorsqu'un site web affiche des informations à partir d'une base de données, il utilise souvent une API pour récupérer ces données de façon structurée et sécurisée. Les API REST constituent aujourd'hui le standard pour les échanges web, utilisant les méthodes HTTP (GET, POST, PUT, DELETE) pour structurer les opérations.",
      "",
      "## Architecture et Technologies Backend",
      "",
      "### Node.js et TypeScript : Le Cœur du Développement Moderne",
      "",
      "Node.js révolutionne le développement backend en permettant l'exécution de JavaScript côté serveur. Cette technologie offre plusieurs avantages : un écosystème riche via npm (Node Package Manager), une performance élevée grâce à son moteur V8, et la possibilité d'utiliser le même langage côté client et serveur.",
      "",
      "TypeScript, qui étend JavaScript avec un système de types statiques, apporte une robustesse supplémentaire. Il permet de détecter les erreurs de compilation avant l'exécution, améliore l'intellisense dans les IDE, et facilite la maintenance des applications complexes.",
      "",
      "### Architecture MVC et Séparation des Responsabilités",
      "",
      "L'architecture MVC (Model-View-Controller) structure le code en trois couches distinctes : les Modèles gèrent les données et la logique métier, les Vues s'occupent de la présentation (souvent déléguée au frontend), et les Contrôleurs orchestrent les interactions entre ces composants.",
      "",
      "Les middlewares constituent un concept fondamental dans les frameworks comme Express.js. Ces fonctions interceptent et traitent les requêtes HTTP avant qu'elles n'atteignent les contrôleurs, permettant l'authentification, la validation, la gestion des erreurs ou encore la limitation des requêtes (rate limiting).",
      "",
      "## Exemples Concrets d'Implémentation",
      "",
      "### Système de Restitution de Matériel",
      "",
      "Pour le système de restitution de matériel, l'API développée en Node.js et TypeScript centralise toutes les opérations. Le script automatisé gère les relances par email en utilisant des bibliothèques comme Nodemailer, tandis que l'API se contente de partager les données de restitution avec le frontend React. Cette séparation claire des responsabilités permet une maintenance aisée et une évolutivité optimale.",
      "",
      "L'architecture utilise des contrôleurs spécialisés pour chaque entité (utilisateurs, matériels, restitutions), des middlewares pour l'authentification JWT (JSON Web Tokens), et des schémas de validation Joi pour garantir l'intégrité des données.",
      "",
      "### Chronos : Gestion Avancée des Réservations",
      "",
      "Pour Chronos, l'API gère la complexité des réservations en temps réel grâce à des endpoints RESTful bien structurés. La gestion des conflits utilise des verrous optimistes en base de données, les notifications temps réel s'appuient sur WebSockets, et le système d'autorisation implémente le pattern RBAC (Role-Based Access Control).",
      "",
      "## Scripts et Automatisation",
      "",
      "Node.js excelle dans l'automatisation grâce à sa nature asynchrone et non-bloquante. Les scripts développés utilisent des patterns comme les Promises et async/await pour gérer les opérations asynchrones, des bibliothèques comme cron pour la planification de tâches, et des outils de templating pour la génération dynamique de contenus.",
      "",
      "## Technologies et Outils Essentiels",
      "",
      "### Validation et Sécurité",
      "",
      "La validation des données s'effectue via des bibliothèques spécialisées comme Joi, Zod ou class-validator. Ces outils permettent de définir des schémas complexes, de valider les types de données, et de générer des messages d'erreur explicites.",
      "",
      "La sécurisation implique l'utilisation de helmet.js pour les headers HTTP, bcrypt pour le hachage des mots de passe, et des stratégies d'authentification comme Passport.js pour gérer OAuth, JWT ou les sessions classiques.",
      "",
      "### Documentation et Tests",
      "",
      "La documentation des API utilise des standards comme OpenAPI/Swagger, permettant de générer une documentation interactive et des clients automatiques. Les annotations TypeScript enrichissent cette documentation avec des informations de typage précises.",
      "",
      "Les tests s'organisent en plusieurs niveaux : tests unitaires avec Jest, tests d'intégration pour les endpoints API, et tests de charge avec des outils comme Artillery pour valider les performances.",
      "",
      "### Gestion des Erreurs et Monitoring",
      "",
      "La gestion centralisée des erreurs utilise des middlewares spécialisés qui interceptent les exceptions, les loggent avec des outils comme Winston, et renvoient des réponses HTTP standardisées. Le monitoring s'appuie sur des métriques applicatives et des outils de surveillance comme PM2 en production.",
      "",
      "## Bonnes Pratiques Techniques",
      "",
      "L'adoption de patterns comme le Repository Pattern sépare la logique d'accès aux données de la logique métier. Les Services encapsulent la logique complexe et favorisent la réutilisabilité. Le Dependency Injection Container facilite les tests et réduit le couplage entre composants.",
      "",
      "La gestion des environnements utilise des variables d'environnement et des fichiers de configuration distincts pour le développement, les tests et la production. Cette approche garantit la portabilité et la sécurité des applications.",
      "",
      "## Conclusion",
      "",
      "Ces expériences techniques illustrent la richesse du développement backend moderne. De l'architecture Node.js/TypeScript à l'implémentation de patterns avancés, en passant par l'automatisation et la sécurisation, chaque projet renforce la maîtrise des technologies et concepts essentiels. Cette expertise technique backend constitue le fondement de la réussite de projets comme la restitution de matériel ou Chronos, démontrant l'importance d'une infrastructure solide et bien conçue.",
    ].join("\n"),
    date: "2025-06-13",
    category: "technical",
    readTime: 7,
    image: devBackend,
    skills: [
      "Node.js",
      "TypeScript",
      "API REST",
      "Backend",
      "Sécurité",
      "Automatisation",
      "Tests",
      "Architecture logicielle",
    ],
  },
  {
    id: 14,
    title: "Coder proprement : la compétence transverse qui change tout",
    slug: "coder-proprement-competence-transverse",
    excerpt:
      "Pourquoi le code propre est la base de tous mes projets, et comment j’utilise conventions, outils et programmation fonctionnelle pour garantir qualité, collaboration et évolutivité.",
    content: [
      "Le code propre est bien plus qu’une simple bonne pratique : c’est une philosophie qui guide tous mes projets, du travail étudiant au développement professionnel. Cette compétence transverse me permet de livrer des solutions robustes, maintenables et compréhensibles par tous, quel que soit le contexte technique ou l’équipe.",
      "",
      "## Une philosophie de développement",
      "",
      "Dès mes débuts en programmation, j’ai compris que la lisibilité et la clarté du code sont essentielles, surtout en équipe. Un code bien écrit facilite la collaboration, accélère la prise en main par de nouveaux développeurs et limite les erreurs lors des évolutions. Coder proprement, c’est écrire du code qui fonctionne, mais surtout du code que l’on peut relire, corriger et faire évoluer facilement.",
      "",
      "## Mes principes fondamentaux",
      "",
      "- **Nommage explicite** : chaque variable ou fonction porte un nom qui reflète clairement son rôle. Cela évite les ambiguïtés et rend le code auto-documenté.",
      "- **Fonctions focalisées** : une fonction = une responsabilité. Cette approche simplifie les tests, la maintenance et la compréhension du code.",
      "- **Organisation cohérente** : dossiers et fichiers structurés logiquement, architecture claire et évolutive. Cela permet à n’importe quel développeur de s’y retrouver rapidement.",
      "",
      "## L’expérience du travail en équipe",
      "",
      "Lors de mes projets étudiants, j’ai vu l’importance de conventions communes pour éviter le chaos. Sans règles partagées, chacun écrit dans son style et le projet devient vite ingérable. Nous avons donc mis en place des conventions de nommage, des standards de structure et des outils pour automatiser la qualité.",
      "",
      "## Outils incontournables : ESLint et Prettier",
      "",
      "- **ESLint** : détecte en temps réel les erreurs et les écarts aux conventions. C’est comme un correcteur orthographique pour le code, qui garantit un standard de qualité constant.",
      "- **Prettier** : applique automatiquement un formatage uniforme à tout le code. Plus de discussions sur l’indentation ou les espaces, tout est standardisé.",
      "",
      "Grâce à ces outils, le code reste homogène, les conflits de style disparaissent et la collaboration devient plus fluide. Les merge conflicts liés au formatage sont quasiment éliminés.",
      "",
      "## Programmation fonctionnelle pour la clarté",
      "",
      "J’intègre aussi les principes de la programmation fonctionnelle (fonctions pures, immutabilité) dans mes projets JavaScript et TypeScript. Cela rend le code plus prévisible, plus facile à tester et limite les effets de bord. Par exemple, je privilégie la création de nouvelles structures de données plutôt que la modification en place.",
      "",
      "## Application concrète dans tous mes projets",
      "",
      "- **Projets personnels** : même seul, je maintiens ces standards pour faciliter la reprise du code plus tard.",
      "- **Projets étudiants** : la clarté du code facilite la collaboration, réduit les conflits techniques et améliore la qualité globale du livrable.",
      "- **Projets professionnels** : cette rigueur est remarquée et appréciée, elle démontre mon professionnalisme et ma capacité à travailler efficacement en équipe.",
      "",
      "## Les bénéfices observés",
      "",
      "- **Productivité accrue** : moins de temps perdu à déchiffrer du code ancien ou mal écrit.",
      "- **Collaboration fluide** : les autres développeurs comprennent rapidement mon travail et peuvent contribuer efficacement.",
      "- **Maintenance simplifiée** : corriger un bug ou ajouter une fonctionnalité devient beaucoup plus simple.",
      "- **Réputation professionnelle** : cette rigueur est remarquée par mes collaborateurs et superviseurs.",
      "",
      "## Une compétence évolutive",
      "",
      "Je considère cette compétence comme évolutive. Chaque projet m’apprend quelque chose de nouveau sur la façon d’améliorer encore la qualité de mon code. Je reste à l’affût des nouvelles pratiques, des nouveaux outils, et j’adapte constamment mes méthodes. Que je travaille en JavaScript, Python ou tout autre langage, les principes restent les mêmes : clarté, cohérence, et souci du détail.",
      "",
      "## Conclusion",
      "",
      "Coder proprement n’est pas qu’une compétence technique, c’est une philosophie de travail qui imprègne tous mes projets. Cette approche, combinée aux outils modernes comme ESLint et Prettier, me permet de maintenir un niveau de qualité constant et de collaborer efficacement avec n’importe quelle équipe. Cette compétence transverse est devenue ma signature en tant que développeur, et je continue à la perfectionner avec chaque nouveau projet.",
    ].join("\n"),
    date: "2025-06-13",
    category: "technical",
    readTime: 7,
    image: coderPrepremnt,
    skills: [
      "Code propre",
      "ESLint",
      "Prettier",
      "Programmation fonctionnelle",
      "Collaboration",
      "Qualité logicielle",
      "Maintenance",
    ],
  },
  {
    id: 15,
    title:
      "L'Ergonomie et l'UX : Ma Vision du Développement Centré Utilisateur",
    slug: "ergonomie-ux-developpement-centre-utilisateur",
    excerpt:
      "Pourquoi l’ergonomie et l’expérience utilisateur sont au cœur de ma démarche de développement, et comment je conçois des applications pensées avant tout pour l’humain.",
    content: [
      "Dans ma pratique du développement, je ne me contente pas d'écrire du code qui fonctionne. Ma priorité, c'est de créer des applications qui offrent une expérience utilisateur exceptionnelle. Cette approche centrée sur l'ergonomie et l'UX (User Experience) est devenue ma signature professionnelle et guide chacune de mes décisions de développement.",
      "",
      "Pour moi, développer une application sans penser à l'utilisateur final, c'est comme construire une maison sans réfléchir à ceux qui vont y vivre. Techniquement parfaite, mais invivable au quotidien.",
      "",
      "## Ma Philosophie : L'Utilisateur au Centre de Tout",
      "",
      'Quand j\'aborde un nouveau projet, ma première question n\'est pas "comment vais-je coder ça ?" mais plutôt "comment l\'utilisateur va-t-il interagir avec cette fonctionnalité ?" Cette approche transforme complètement la façon dont je conçois et développe mes applications.',
      "",
      "Je pense constamment ergonomie et UX. Chaque bouton, chaque menu, chaque transition est pensé du point de vue de l'utilisateur. Est-ce que c'est intuitif ? Est-ce que ça répond à un besoin réel ? Est-ce que ça simplifie ou complique la tâche ?",
      "",
      "## Comprendre l'Ergonomie d'une Application",
      "",
      "L'ergonomie d'une application, c'est sa capacité à être utilisée facilement et efficacement par ses utilisateurs. C'est la différence entre une application qu'on utilise avec plaisir et une autre qu'on abandonne après cinq minutes de frustration.",
      "",
      "**L'ergonomie, c'est l'art de rendre simple ce qui pourrait être compliqué.**",
      "",
      "Dans mes projets, je m'attache à plusieurs principes fondamentaux :",
      "",
      '**Clarté avant tout**  \nChaque élément de l\'interface doit avoir un rôle évident. Un utilisateur ne devrait jamais se demander "à quoi sert ce bouton ?" ou "où dois-je cliquer ?". Je conçois mes interfaces comme des panneaux de signalisation : claires, directes, sans ambiguïté.',
      "",
      "**Simplicité d'utilisation**  \nPlus c'est simple, mieux c'est. Je privilégie toujours la solution la plus directe pour accomplir une tâche. Si l'utilisateur doit faire cinq clics pour quelque chose qui pourrait se faire en deux, je repense mon approche.",
      "",
      "**Cohérence dans l'expérience**  \nDans toutes mes applications, les éléments similaires fonctionnent de la même façon. Si un bouton rouge signifie \"supprimer\" sur une page, il aura la même signification partout dans l'application. Cette cohérence rassure l'utilisateur et accélère son apprentissage.",
      "",
      "## Mon Processus de Réflexion UX",
      "",
      "**Je me mets dans la peau de l'utilisateur**  \nQui va utiliser cette application ? Dans quel contexte ? Avec quels objectifs ? Ces questions orientent toutes mes décisions de design et de développement.",
      "",
      "**Je dessine avant de coder**  \nJe crée souvent des croquis rapides ou des wireframes pour visualiser l'expérience utilisateur. Cela m'évite de me lancer dans le code sans avoir une vision claire de l'interface finale.",
      "",
      "**Je teste régulièrement**  \nTout au long du développement, je teste mes interfaces avec de vraies personnes. Leurs réactions m'aident à identifier les problèmes d'ergonomie avant qu'ils ne deviennent des obstacles majeurs.",
      "",
      "## Exemples Concrets de Mon Approche",
      "",
      "**Navigation intuitive**  \nDans mes applications, je conçois la navigation comme un GPS : elle doit guider naturellement l'utilisateur vers son objectif. Menus clairs, fil d'Ariane visible, retours possibles à tout moment.",
      "",
      "**Gestion des erreurs humaine**  \nQuand un utilisateur fait une erreur, je ne me contente pas d'afficher \"Erreur 404\". J'explique ce qui s'est passé en termes simples et je propose une solution concrète pour continuer.",
      "",
      "**Feedback immédiat**  \nChaque action de l'utilisateur provoque une réaction visible de l'interface. Bouton qui change de couleur au survol, message de confirmation après une action, indicateur de chargement : l'utilisateur sait toujours ce qui se passe.",
      "",
      "**Accessibilité par défaut**  \nJe pense à tous les utilisateurs, y compris ceux qui ont des besoins spécifiques. Contrastes suffisants, navigation au clavier possible, textes alternatifs pour les images : l'inclusivité fait partie de ma définition de la bonne UX.",
      "",
      "## L'Impact sur Mes Projets",
      "",
      "**Adoption plus rapide**  \nLes utilisateurs s'approprient plus facilement mes applications parce qu'elles sont conçues pour eux, pas contre eux.",
      "",
      "**Moins de support technique**  \nUne interface bien pensée génère moins de questions et de problèmes. Les utilisateurs trouvent naturellement ce qu'ils cherchent.",
      "",
      "**Satisfaction utilisateur**  \nLes retours que je reçois portent sur les fonctionnalités plutôt que sur les difficultés d'utilisation. C'est le signe d'une bonne ergonomie.",
      "",
      "**Différenciation professionnelle**  \nCette approche me distingue d'autres développeurs qui se concentrent uniquement sur l'aspect technique. Elle démontre ma compréhension globale des enjeux d'un projet digital.",
      "",
      "## Les Défis de Cette Approche",
      "",
      "Penser constamment ergonomie et UX demande plus de temps en amont, mais c'est un investissement qui se révèle toujours payant. Parfois, la solution techniquement la plus simple n'est pas la plus ergonomique, et il faut trouver des compromis intelligents.",
      "",
      "Cette approche demande aussi de résister à la tentation d'ajouter des fonctionnalités \"parce que c'est possible techniquement\". Chaque élément doit avoir une justification du point de vue utilisateur.",
      "",
      "## Une Approche Évolutive",
      "",
      "Ma vision de l'ergonomie et de l'UX continue d'évoluer avec chaque projet. Je m'inspire des meilleures pratiques du marché, j'observe comment les utilisateurs interagissent avec les interfaces populaires, et j'adapte constamment mes méthodes.",
      "",
      "Je considère que cette dimension de mon travail est aussi importante que mes compétences techniques. C'est elle qui transforme une application fonctionnelle en une application que les gens ont envie d'utiliser.",
      "",
      "## L'Équilibre entre Technique et Humain",
      "",
      "Mon approche consiste à faire le pont entre l'excellence technique et l'expérience humaine. Je maîtrise les aspects techniques du développement, mais je les mets toujours au service d'une expérience utilisateur réfléchie et optimisée.",
      "",
      "Cette double compétence - technique et UX - me permet de développer des applications qui ne sont pas seulement bien codées, mais aussi agréables et efficaces à utiliser.",
      "",
      "## Conclusion",
      "",
      "Penser ergonomie et UX n'est pas une contrainte dans mon processus de développement, c'est ce qui donne du sens à mon travail. Chaque ligne de code que j'écris a pour objectif final d'améliorer la vie de quelqu'un qui utilisera l'application.",
      "",
      "Cette approche centrée utilisateur est devenue ma marque de fabrique. Elle guide mes choix techniques, influence mes décisions de design, et transforme mes projets en expériences mémorables pour leurs utilisateurs.",
      "",
      "Parce qu'au final, la meilleure technologie du monde ne sert à rien si personne ne sait ou ne veut l'utiliser.",
    ].join("\n"),
    date: "2025-06-13",
    category: "transversal",
    readTime: 10,
    image: ergonomie,
    skills: [
      "Ergonomie",
      "UX",
      "Accessibilité",
      "Design d'interface",
      "Tests utilisateurs",
      "Simplicité",
      "Clarté",
      "Feedback utilisateur",
      "Adoption",
    ],
  },
  {
    id: 16,
    title:
      "Le Développement Frontend : Mes Compétences au Service de l'Interface Utilisateur",
    slug: "developpement-frontend-interface-utilisateur",
    excerpt:
      "Maîtrise de HTML, CSS, JavaScript, React et Next.js pour concevoir des interfaces web modernes, performantes et centrées utilisateur.",
    content: [
      "Le développement frontend, c'est tout ce que l'utilisateur voit et avec quoi il interagit quand il utilise une application web. Si on compare une application à un iceberg, le frontend c'est la partie visible au-dessus de l'eau, celle avec laquelle on interagit directement.",
      "",
      "Contrairement au backend qui gère les données et la logique métier en arrière-plan, le frontend s'occupe de l'interface utilisateur, des interactions, des animations, et de l'expérience visuelle. C'est le pont entre l'utilisateur et toute la puissance technique qui se cache derrière.",
      "",
      "Dans ma pratique du développement, je maîtrise les technologies essentielles de cet univers : HTML, CSS, JavaScript, React et Next.js. Chacune de ces compétences joue un rôle crucial dans la création d'applications web modernes et performantes.",
      "",
      "## HTML : La Structure de Tout",
      "",
      "HTML (HyperText Markup Language) est le squelette de toute page web. C'est le langage qui structure le contenu et définit la hiérarchie des informations.",
      "",
      "**Comment ça fonctionne ?**",
      "HTML utilise des balises pour délimiter différents éléments : titres, paragraphes, images, liens, formulaires. C'est comme construire une maison en définissant d'abord où vont les murs, les portes et les fenêtres.",
      "",
      "**Pourquoi c'est essentiel ?**",
      "Sans HTML, il n'y a pas de page web. C'est la base absolue. Mais bien maîtriser HTML, c'est aussi comprendre l'accessibilité, le référencement (SEO), et la sémantique du web. Une structure HTML bien pensée facilite la navigation pour tous les utilisateurs, y compris ceux qui utilisent des technologies d'assistance.",
      "",
      "Dans mes projets, je porte une attention particulière à la sémantique HTML. J'utilise les bonnes balises au bon endroit, ce qui améliore l'accessibilité et aide les moteurs de recherche à comprendre le contenu.",
      "",
      "## CSS : L'Art de la Présentation",
      "",
      "CSS (Cascading Style Sheets) transforme la structure HTML brute en interface attractive et fonctionnelle. Si HTML est le squelette, CSS est tout le reste : la peau, les vêtements, la décoration.",
      "",
      "**Comment ça fonctionne ?**",
      "CSS permet de définir l'apparence de chaque élément : couleurs, tailles, positions, animations. Il peut transformer une page HTML basique en une expérience visuelle riche et engageante.",
      "",
      "**Pourquoi c'est essentiel ?**",
      "CSS ne se contente pas de rendre les choses \"jolies\". Il gère aussi l'ergonomie, la lisibilité, l'adaptabilité aux différents écrans (responsive design), et l'identité visuelle de l'application.",
      "",
      "Ma maîtrise de CSS me permet de créer des interfaces qui s'adaptent parfaitement à tous les appareils, du smartphone à l'écran d'ordinateur. Je peux également implémenter des animations fluides qui améliorent l'expérience utilisateur sans surcharger l'interface.",
      "",
      "## JavaScript : Le Moteur de l'Interactivité",
      "",
      "JavaScript est le langage de programmation qui donne vie aux pages web. Si HTML est le squelette et CSS l'apparence, JavaScript est le système nerveux qui permet aux pages de réagir, de bouger et d'interagir.",
      "",
      "**Comment ça fonctionne ?**",
      "JavaScript s'exécute directement dans le navigateur et peut modifier en temps réel le contenu d'une page, réagir aux actions de l'utilisateur (clics, saisie, survol), et communiquer avec des serveurs pour récupérer ou envoyer des données.",
      "",
      "**Pourquoi c'est essentiel ?**",
      "Sans JavaScript, les pages web seraient statiques comme des brochures papier. JavaScript transforme une page web en une application interactive. C'est lui qui permet de valider un formulaire en temps réel, d'afficher des notifications, de créer des carrousels d'images, ou de mettre à jour le contenu sans recharger la page.",
      "",
      "Dans mes projets, JavaScript me permet de créer des expériences utilisateur riches et dynamiques. Je l'utilise pour gérer les interactions complexes, les animations personnalisées, et la logique métier côté client. Ma maîtrise de JavaScript est également la base qui me permet d'utiliser efficacement React et Next.js.",
      "",
      "## React : La Révolution des Interfaces Dynamiques",
      "",
      "React est une bibliothèque JavaScript créée par Facebook qui a révolutionné la façon de créer des interfaces utilisateur interactives.",
      "",
      "**Comment ça fonctionne ?**",
      "React fonctionne avec des \"composants\" - des blocs de code réutilisables qui combinent structure (HTML), présentation (CSS) et comportement (JavaScript). C'est comme avoir des briques de construction intelligentes qu'on peut assembler pour créer des interfaces complexes.",
      "",
      "**Pourquoi c'est essentiel ?**",
      "React permet de créer des applications web qui réagissent instantanément aux actions de l'utilisateur. Plus besoin de recharger la page entière quand on clique sur un bouton : seule la partie concernée se met à jour. C'est ce qui rend les applications web modernes aussi fluides que les applications mobiles.",
      "",
      "Dans mes projets React, je crée des composants réutilisables qui accélèrent le développement et garantissent la cohérence de l'interface. Par exemple, si je crée un composant \"Bouton\", je peux le réutiliser partout dans l'application avec différentes couleurs ou tailles, sans réécrire le code.",
      "",
      "## Next.js : La Puissance du React Optimisé",
      "",
      "Next.js est un framework basé sur React qui ajoute des fonctionnalités avancées pour créer des applications web performantes et optimisées.",
      "",
      "**Comment ça fonctionne ?**",
      "Next.js prend React et y ajoute des capacités comme le rendu côté serveur, la génération de sites statiques, l'optimisation automatique des images, et la gestion intelligente des routes. C'est React avec des super-pouvoirs.",
      "",
      "**Pourquoi c'est essentiel ?**",
      "Next.js résout les problèmes de performance et de référencement qui peuvent survenir avec React classique. Il génère des applications plus rapides, mieux référencées par Google, et plus facilement déployables.",
      "",
      "Avec Next.js, je peux créer des applications qui se chargent très rapidement, même sur des connexions lentes. Le framework optimise automatiquement beaucoup d'aspects techniques, me permettant de me concentrer sur l'expérience utilisateur.",
      "",
      "## L'Écosystème Complet : Comment Tout S'Articule",
      "",
      "Ces cinq technologies forment un écosystème cohérent dans mes projets :",
      "",
      "**HTML** pose les fondations sémantiques",
      "**CSS** créé l'expérience visuelle et l'ergonomie",
      "**JavaScript** apporte la logique et l'interactivité",
      "**React** structure et organise les interfaces complexes",
      "**Next.js** optimise les performances et la production",
      "",
      "Cette combinaison me permet de créer des applications web complètes, depuis la conception de l'interface jusqu'au déploiement en production.",
      "",
      "## Pourquoi Ces Compétences Sont Essentielles",
      "",
      "**Pour l'utilisateur final :**",
      "Ces technologies permettent de créer des applications rapides, intuitives et agréables à utiliser. L'utilisateur bénéficie d'une expérience fluide et moderne.",
      "",
      "**Pour l'entreprise :**",
      "Une interface bien développée améliore l'engagement des utilisateurs, réduit les coûts de support, et peut directement impacter les revenus. Une boutique en ligne avec une interface fluide vend plus qu'une interface compliquée.",
      "",
      "**Pour l'équipe de développement :**",
      "Un code frontend bien structuré avec React et Next.js est plus facile à maintenir, à faire évoluer, et permet de développer plus rapidement de nouvelles fonctionnalités.",
      "",
      "## Ma Valeur Ajoutée",
      "",
      "**Polyvalence technique :** Je peux prendre en charge l'intégralité de la partie frontend d'un projet, de la conception à la mise en production.",
      "",
      "**Optimisation des performances :** Grâce à Next.js, je crée des applications qui se chargent rapidement et offrent une expérience utilisateur optimale.",
      "",
      "**Code maintenable :** Mon approche avec React privilégie la création de composants réutilisables et bien structurés, facilitant la maintenance et l'évolution du projet.",
      "",
      "**Responsive design :** Mes compétences CSS garantissent que les applications fonctionnent parfaitement sur tous les appareils.",
      "",
      "## L'Évolution Constante du Frontend",
      "",
      "Le développement frontend évolue rapidement, et je maintiens mes compétences à jour avec les dernières pratiques et outils. Cette veille technologique me permet de proposer des solutions modernes et performantes.",
      "",
      "Ces technologies continuent d'évoluer : React introduit régulièrement de nouvelles fonctionnalités, Next.js améliore constamment ses performances, et les standards web évoluent. Cette évolution constante rend le métier passionnant et me pousse à me perfectionner continuellement.",
      "",
      "## Impact Concret sur les Projets",
      "",
      "**Des interfaces utilisateur intuitives** qui réduisent la courbe d'apprentissage",
      "**Des performances optimisées** qui améliorent l'engagement des utilisateurs",
      "**Une maintenance facilitée** grâce à un code bien structuré",
      "**Une compatibilité multi-appareils** qui élargit l'audience potentielle",
      "",
      "## Conclusion",
      "",
      "Le développement frontend n'est pas juste une question de \"faire du joli\". C'est une discipline technique complexe qui demande la maîtrise de multiples technologies et une compréhension approfondie des besoins utilisateurs.",
      "",
      "Ma expertise en HTML, CSS, JavaScript, React et Next.js me permet de créer des applications web modernes qui allient performance technique et expérience utilisateur exceptionnelle. Ces compétences sont essentielles dans le développement d'applications car elles déterminent la première impression et l'adoption par les utilisateurs.",
      "",
      "Dans un monde où l'expérience utilisateur fait la différence entre le succès et l'échec d'une application, maîtriser le développement frontend est devenu indispensable pour tout développeur qui souhaite créer des solutions complètes et impactantes.",
    ].join("\n"),
    date: "2025-06-13",
    category: "technical",
    readTime: 10,
    image: devFrontend,
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Next.js",
      "Responsive design",
      "Accessibilité",
      "Performance",
      "UI/UX",
      "Composants réutilisables",
    ],
  },
  {
    id: 17,
    title: "Compétence Transverse : Rigueur",
    slug: "competence-transverse-rigueur",
    excerpt:
      "La rigueur, c’est l’art d’appliquer une méthode précise et constante, aussi bien dans le développement logiciel que dans la pratique sportive, pour garantir fiabilité, qualité et amélioration continue.",
    content: [
      "La rigueur se caractérise par une approche méthodique, précise et systématique dans l'exécution des tâches. Elle implique le respect strict des processus, l'attention aux détails et la constance dans l'effort pour atteindre l'excellence.",
      "",
      "## Manifestations concrètes",
      "",
      "### Dans le développement logiciel",
      "",
      "- **Code propre et structuré** : Application systématique des bonnes pratiques de programmation, respect des conventions de nommage et architecture modulaire",
      "- **Tests et validation** : Mise en place rigoureuse de tests unitaires, d'intégration et de validation pour garantir la fiabilité du code",
      "- **Documentation technique** : Rédaction précise et complète de la documentation, commentaires de code explicites",
      "- **Gestion des versions** : Utilisation méthodique des outils de versioning avec des commits clairs et structurés",
      "- **Debugging méthodique** : Approche systématique pour identifier et résoudre les problèmes techniques",
      "- **Ergonomie et UX rigoureuse** : Conception d'interfaces utilisateur avec attention méticuleuse aux détails d'interaction, respect strict des principes d'accessibilité et d'utilisabilité, tests utilisateurs systématiques pour valider chaque élément de l'expérience",
      "",
      "### Dans la pratique sportive (Sprint)",
      "",
      "- **Préparation physique structurée** : Planification rigoureuse des entraînements, respect des phases de récupération et progression méthodique",
      "- **Analyse technique** : Étude précise des gestes techniques, correction systématique des défauts de course",
      "- **Suivi des performances** : Mesure et analyse rigoureuse des temps, identification des axes d'amélioration",
      "- **Discipline personnelle** : Respect strict des horaires d'entraînement, de l'alimentation et du repos",
      "- **Préparation mentale** : Approche méthodique de la concentration et de la gestion du stress en compétition",
      "",
      "## Valeur ajoutée transverse",
      "",
      "Cette compétence en rigueur développée dans deux domaines complémentaires (technique et sportif) apporte :",
      "",
      "- **Fiabilité exceptionnelle** : Capacité à produire des résultats constants et de qualité",
      "- **Gestion de la pression** : Maintien de la précision même dans des environnements exigeants",
      "- **Amélioration continue** : Approche systématique pour identifier et corriger les points faibles",
      "- **Respect des délais** : Planification rigoureuse permettant de tenir les échéances",
      "- **Qualité constante** : Standards élevés maintenus dans toutes les activités entreprises",
      "",
      "## Applications professionnelles",
      "",
      "Cette double expertise en rigueur permet d'exceller dans :",
      "- La gestion de projets complexes nécessitant précision et méthode",
      "- Le développement d'applications critiques où l'erreur n'est pas permise",
      "- L'encadrement d'équipes en transmettant les bonnes pratiques",
      "- La résolution de problèmes complexes par une approche méthodique",
      "- L'optimisation des processus pour améliorer l'efficacité globale",
    ].join("\n"),
    date: "2025-06-13",
    category: "transversal",
    readTime: 7,
    image: rigueur,
    skills: [
      "Rigueur",
      "Méthode",
      "Qualité",
      "Amélioration continue",
      "Gestion de projet",
      "Discipline",
      "Fiabilité",
      "Tests",
      "Documentation",
      "Analyse technique",
    ],
  },
  {
    id: 18,
    title: "Compétence Transverse : Esprit Critique",
    slug: "competence-transverse-esprit-critique",
    excerpt:
      "L'esprit critique, c'est la capacité à analyser, questionner et améliorer les choix techniques, UX et stratégiques, aussi bien dans le développement web que dans la pratique sportive.",
    content: [
      "# Compétence Transverse : Esprit Critique",
      "",
      "## Définition",
      "",
      "L'esprit critique consiste à analyser, évaluer et questionner de manière objective les informations, les processus et les décisions. Il implique une capacité à prendre du recul, à identifier les biais et à proposer des solutions alternatives basées sur une réflexion approfondie.",
      "",
      "## Manifestations concrètes",
      "",
      "### Dans le développement web",
      "",
      "- **Analyse architecturale** : Évaluation critique des choix techniques web, remise en question des patterns établis pour optimiser les performances et la maintenabilité des applications",
      "- **Code review exigeant** : Examen méticuleux du code frontend/backend avec questionnement constructif des implémentations, identification des points d'amélioration",
      "- **Optimisation UX/UI web** : Analyse critique de l'expérience utilisateur sur les interfaces web, remise en question des conventions d'ergonomie pour améliorer l'accessibilité et l'utilisabilité",
      "- **Choix de stack technique** : Évaluation objective des frameworks JavaScript, librairies CSS et outils de développement, comparaison critique des alternatives",
      "- **Performance web critique** : Questionnement systématique des temps de chargement, analyse des métriques Core Web Vitals et optimisation basée sur les données",
      "- **Responsive design analytique** : Remise en question critique des breakpoints et approches mobile-first pour garantir une expérience optimale sur tous les devices",
      "- **SEO et accessibilité** : Analyse critique du référencement naturel et de l'accessibilité web, questionnement des pratiques pour respecter les standards WCAG",
      "",
      "### Dans la pratique sportive (Sprint)",
      "",
      "- **Auto-analyse technique** : Évaluation critique de sa propre technique de course, identification des points faibles sans complaisance",
      "- **Analyse tactique** : Étude critique des stratégies de course, remise en question des habitudes pour optimiser les performances",
      "- **Évaluation des méthodes d'entraînement** : Questionnement des programmes traditionnels, recherche d'approches alternatives plus efficaces",
      "- **Analyse de la concurrence** : Étude objective des forces et faiblesses des adversaires pour adapter sa stratégie",
      "- **Feedback constructif** : Capacité à recevoir et intégrer les critiques de l'entraîneur tout en gardant un regard analytique",
      "- **Préparation mentale** : Remise en question critique de ses propres croyances limitantes et biais cognitifs",
      "",
      "## Valeur ajoutée transverse",
      "",
      "Cette compétence en esprit critique développée dans deux domaines complémentaires apporte :",
      "",
      "- **Vision objective** : Capacité à analyser les situations sans être influencé par les émotions ou les préjugés",
      "- **Innovation par questionnement** : Remise en cause constructive des méthodes établies pour proposer des améliorations",
      "- **Prise de décision éclairée** : Évaluation rigoureuse des options avant de choisir la meilleure solution",
      "- **Adaptabilité intelligente** : Capacité à remettre en question ses propres approches quand la situation l'exige",
      "- **Leadership par l'exemple** : Influence positive sur les équipes en encourageant la réflexion critique",
      "",
      "## Applications professionnelles",
      "",
      "Cette double expertise en esprit critique permet d'exceller dans :",
      "- L'audit et l'amélioration d'applications web existantes",
      "- La conduite de projets de refonte web nécessitant de repenser les approches UX/UI",
      "- Le management d'équipes de développement en favorisant une culture de questionnement constructif",
      "- La résolution de problèmes de performance web par une approche analytique multicritère",
      "- La veille technologique web et l'évaluation critique des nouvelles tendances frontend/backend",
      "- La conception d'expériences utilisateur web en remettant en question les conventions d'interface établies",
    ].join("\n"),
    date: "2025-06-13",
    category: "transversal",
    readTime: 8,
    image: espritCritique,
    skills: [
      "Esprit critique",
      "Analyse",
      "Questionnement",
      "UX/UI",
      "Performance web",
      "SEO",
      "Accessibilité",
      "Refonte",
      "Leadership",
      "Innovation",
    ],
  },
];

export const projectsData: Project[] = [
  {
    id: 1,
    title: "Space monopoly",
    description:
      "Un jeu de société bureau sur le thème de l'espace, inspiré du Monopoly en 3D.",
    technologies: ["Java", "JavaFX", "Blender"],
    image: spaceMonopoly,
    videoUrl: "https://www.youtube.com/watch?v=sZujKdlejeA&ab_channel=Jeremie",
    category: "Student",
  },
  {
    id: 2,
    title: "Phone market",
    description:
      "Une application de gestion de marché de téléphones, permettant aux utilisateurs d'acheter et de vendre des téléphones.",
    technologies: ["PHP", "MYSQL", "HTML", "CSS", "WAMP"],
    image: phoneMarket,
    videoUrl: "https://www.youtube.com/watch?v=mZ2vzl0wdWY&ab_channel=Jeremie",
    category: "Student",
  },
  {
    id: 3,
    title: "Fastlink",
    description:
      "Un outil de gestion de liens, permettant aux utilisateurs de raccourcir et de partager des liens facilement.",
    technologies: ["Vue.js", "Spring Boot", "Java", "MYSQL", "Architecture Microservices"],
    image: fastlink,
    videoUrl: "https://www.youtube.com/watch?v=J2OWjOt3pQ4",
    category: "Student",
  },
  {
    id: 4,
    title: "Site web ESCXV Athlétisme",
    description: "Site web du club d'athlétisme avec horaires, groupes d'entraînement et lieux de pratique.",
    technologies: ["Next.js", "Vercel"],
    image: escxv,
    demoUrl: "https://www.esc15-athletisme.com",
    category: "Personal",
  }
];
